apiVersion: v1
kind: ConfigMap

metadata:
  name: clinic-config
  namespace: clinic

data:
  Jwt__Issuer: "Zydan"
  Jwt__Audience: "ClinicUsers"
  Jwt__DurationInMinutes: "2880"

  EmailSettings__Host: "smtp.gmail.com"
  EmailSettings__Port: "587"

  Firebase__CredentialsPath: "Firebase/clinic-firebase.json"

  CloudinarySettings__CloudName: "dqzjhlws4"

  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System: "Warning"

  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft_AspNetCore: "Warning"

  AllowedHosts: "*"
