name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore Backend/Clinic.sln

    - name: Build
      run: dotnet build Backend/Clinic.sln -c Release --no-restore

    - name: Run Tests
      run: dotnet test Backend/Clinic.sln -c Release --no-build

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/clinic-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/clinic-api:${{ github.sha }}
    - name: Restart Deployment
      if: github.ref == 'refs/heads/main'
      run: |
        kubectl rollout restart deployment clinic-api -n clinic
